### PR TITLE
fix issue #19

### LINKED ISSUE #19: The cancel of EncryptKeyPrompt is not work properly
The EncryptKeyPrompt allows user to cancel, which indicates the open/save flow should be break.
But in currently, it actually send empty string as password to encrypt/decrypt, that was not a big deal until I hash the password in Encrypt module for allowing non-fixed length password which means we can encrypt/decrypt with empty string and causes the open/save flow doesn't be broken.

### PR DESCRIPTION
**Pull request by zanets**
This pull request mainly fix #19. The biggest change is I add Errors.js for defining custom errors. The better way to check error type and do the proper job is useing instanceof or error code instead of err.toString or message. 

However, I have to mention that instanceof doesn't work properly with class which created by es6 "class extends" under current develop environment, but it works fine in pure nodejs v8.11.2, so it should be an issue of webpack/babel or some magic tools.

And I see different style within modules, such as export/import/require and const/var etc. I try to follow it but it just confused me. My personal opinion is using ES6 style such as import/export instead of module.exports/require and class/extends instead of function. We need to talk about that and  unite all of them.

Oh, I was going to fix this much earlier, but I cannot help playing with my cat. Sorry about that :P

### CODE REVIEW

**Comment by hiro0218** [comment]
Thank you for your fix code.
I will confirm additional code from now.

> And I see different style within modules, such as export/import/require and const/var etc. I try to follow it but it just confused me. My personal opinion is using ES6 style such as import/export instead of module.exports/require and class/extends instead of function. We need to talk about that and unite all of them.

no problem. miikun's code is a legacy.  I plan to rewrite the code in ES6 style in the future.
I am pleased to be able to discuss at a good timing if possible.

> Oh, I was going to fix this much earlier, but I cannot help playing with my cat. Sorry about that :P

haha, If you get bored with playing with a cat, please help me again 🙏✨

File: src/renderer/components/Toolbar.vue [hunk 1]
```diff
@@ -169,7 +169,9 @@ export default {
           return true
         }
       } catch (e) {
-        self.openDialog('error', e)
+        if (e.code !== ERR_USER_CANCEL)) {
```
Comment (hiro0218) [inline src/renderer/components/Toolbar.vue]: Invalid closing parenthesis.

**Review by hiro0218 — CHANGES_REQUESTED** [review]

File: src/renderer/components/Toolbar.vue (hunk 1 above)
Comment (zanets) [reply src/renderer/components/Toolbar.vue]: Ok, got it. 
But the Toolbar doesn't appear on the UI, what should I do to let it show on UI for testing the function on it ?

Comment (hiro0218) [reply src/renderer/components/Toolbar.vue]: Thank you for your fix!

I'm sorry. In the current development branch the toolbar is inactive. I'm planning to revitalize by improving future functions.

**Review by hiro0218 — APPROVED** [review]

File: src/renderer/components/Toolbar.vue (hunk 1 above)
Comment (zanets) [reply src/renderer/components/Toolbar.vue]: Got it. I am expecting that.

**Comment by hiro0218** [comment]
LGTM
